version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  json:
    format: '{"time": "%(asctime)s", "name": "%(name)s", "level": "%(levelname)s", "message": "%(message)s"}'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: logs/app.log
    maxBytes: 10485760  # 10 MB
    backupCount: 5
    encoding: utf8

  json_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/app.json.log
    maxBytes: 10485760  # 10 MB
    backupCount: 5
    encoding: utf8

loggers:
  dagnostics:
    level: DEBUG
    handlers: [console, file]
    propagate: False

  dagnostics.api:
    level: INFO
    handlers: [json_file]
    propagate: False

  dagnostics.cli:
    level: DEBUG
    handlers: [console, file]
    propagate: False

root:
  level: WARNING
  handlers: [console]
